# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-10-30 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0016_coursenrollment_course_on_delete_do_nothing'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='name_en',
            field=models.CharField(blank=True, default=b'', max_length=255, null=True),
        ),
    ]
